[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Ollama", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.ollama"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.ollama"
version = "@toml.version@"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.model.provider.ollama-native"
version = "@toml.version@"
path = "../native/build/libs/ai.model.provider.ollama-native-@project.version@.jar"
