[plugin]
id = "ai-compiler-plugin"
class = "io.ballerina.lib.ai.ollama.AiOllamaCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.model.provider.ollama-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-@ballerinaToOpenApiVersion.version@.jar"
