[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Ollama", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.model.provider.ollama"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.model.provider.ollama"
version = "1.0.1"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.model.provider.ollama-native"
version = "1.0.1"
path = "../native/build/libs/ai.model.provider.ollama-native-1.0.1-SNAPSHOT.jar"
